[project]
name = "mcp-date"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.6.0",
    "pymysql>=1.1.1",
    "requests>=2.32.3",
]
